version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go build
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          command: |
            go test -coverprofile=c.out
            go test ./...
            go test ./... -tags=e2e
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts

      # Download test-reporter
       - run:
           name: Setup Code Climate test-reporter
           command: |
             curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
             chmod +x ./cc-test-reporter

      - store_artifacts:
          path: /tmp/artifacts

      - codecov/upload:
          file: /tmp/artifacts
